/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaticRouteRouteImport } from './routes/_static/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as StaticIndexRouteImport } from './routes/_static/index'
import { Route as StaticDatabaseIndexRouteImport } from './routes/_static/database/index'
import { Route as StaticAuthIndexRouteImport } from './routes/_static/auth/index'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/app/index'
import { Route as StaticDatabaseQueriesRouteImport } from './routes/_static/database/queries'
import { Route as StaticAuthClientRouteImport } from './routes/_static/auth/client'
import { Route as AuthedAppPolarSubscriptionsRouteImport } from './routes/_authed/app/polar/subscriptions'
import { Route as AuthedAppPolarCheckoutSuccessRouteImport } from './routes/_authed/app/polar/checkout.success'
import { ServerRoute as ApiWebhookPolarServerRouteImport } from './routes/api/webhook/polar'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth.$'
import { ServerRoute as AuthedAppPolarPortalServerRouteImport } from './routes/_authed/app/polar/portal'

const rootServerRouteImport = createServerRootRoute()

const StaticRouteRoute = StaticRouteRouteImport.update({
  id: '/_static',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticIndexRoute = StaticIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaticRouteRoute,
} as any)
const StaticDatabaseIndexRoute = StaticDatabaseIndexRouteImport.update({
  id: '/database/',
  path: '/database/',
  getParentRoute: () => StaticRouteRoute,
} as any)
const StaticAuthIndexRoute = StaticAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => StaticRouteRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const StaticDatabaseQueriesRoute = StaticDatabaseQueriesRouteImport.update({
  id: '/database/queries',
  path: '/database/queries',
  getParentRoute: () => StaticRouteRoute,
} as any)
const StaticAuthClientRoute = StaticAuthClientRouteImport.update({
  id: '/auth/client',
  path: '/auth/client',
  getParentRoute: () => StaticRouteRoute,
} as any)
const AuthedAppPolarSubscriptionsRoute =
  AuthedAppPolarSubscriptionsRouteImport.update({
    id: '/app/polar/subscriptions',
    path: '/app/polar/subscriptions',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAppPolarCheckoutSuccessRoute =
  AuthedAppPolarCheckoutSuccessRouteImport.update({
    id: '/app/polar/checkout/success',
    path: '/app/polar/checkout/success',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const ApiWebhookPolarServerRoute = ApiWebhookPolarServerRouteImport.update({
  id: '/api/webhook/polar',
  path: '/api/webhook/polar',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const AuthedAppPolarPortalServerRoute =
  AuthedAppPolarPortalServerRouteImport.update({
    id: '/_authed/app/polar/portal',
    path: '/app/polar/portal',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof StaticIndexRoute
  '/auth/client': typeof StaticAuthClientRoute
  '/database/queries': typeof StaticDatabaseQueriesRoute
  '/app': typeof AuthedAppIndexRoute
  '/auth': typeof StaticAuthIndexRoute
  '/database': typeof StaticDatabaseIndexRoute
  '/app/polar/subscriptions': typeof AuthedAppPolarSubscriptionsRoute
  '/app/polar/checkout/success': typeof AuthedAppPolarCheckoutSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof StaticIndexRoute
  '/auth/client': typeof StaticAuthClientRoute
  '/database/queries': typeof StaticDatabaseQueriesRoute
  '/app': typeof AuthedAppIndexRoute
  '/auth': typeof StaticAuthIndexRoute
  '/database': typeof StaticDatabaseIndexRoute
  '/app/polar/subscriptions': typeof AuthedAppPolarSubscriptionsRoute
  '/app/polar/checkout/success': typeof AuthedAppPolarCheckoutSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_static': typeof StaticRouteRouteWithChildren
  '/_static/': typeof StaticIndexRoute
  '/_static/auth/client': typeof StaticAuthClientRoute
  '/_static/database/queries': typeof StaticDatabaseQueriesRoute
  '/_authed/app/': typeof AuthedAppIndexRoute
  '/_static/auth/': typeof StaticAuthIndexRoute
  '/_static/database/': typeof StaticDatabaseIndexRoute
  '/_authed/app/polar/subscriptions': typeof AuthedAppPolarSubscriptionsRoute
  '/_authed/app/polar/checkout/success': typeof AuthedAppPolarCheckoutSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/client'
    | '/database/queries'
    | '/app'
    | '/auth'
    | '/database'
    | '/app/polar/subscriptions'
    | '/app/polar/checkout/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/client'
    | '/database/queries'
    | '/app'
    | '/auth'
    | '/database'
    | '/app/polar/subscriptions'
    | '/app/polar/checkout/success'
  id:
    | '__root__'
    | '/_authed'
    | '/_static'
    | '/_static/'
    | '/_static/auth/client'
    | '/_static/database/queries'
    | '/_authed/app/'
    | '/_static/auth/'
    | '/_static/database/'
    | '/_authed/app/polar/subscriptions'
    | '/_authed/app/polar/checkout/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  StaticRouteRoute: typeof StaticRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/webhook/polar': typeof ApiWebhookPolarServerRoute
  '/app/polar/portal': typeof AuthedAppPolarPortalServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/webhook/polar': typeof ApiWebhookPolarServerRoute
  '/app/polar/portal': typeof AuthedAppPolarPortalServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/webhook/polar': typeof ApiWebhookPolarServerRoute
  '/_authed/app/polar/portal': typeof AuthedAppPolarPortalServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/webhook/polar' | '/app/polar/portal'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/webhook/polar' | '/app/polar/portal'
  id:
    | '__root__'
    | '/api/auth/$'
    | '/api/webhook/polar'
    | '/_authed/app/polar/portal'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiWebhookPolarServerRoute: typeof ApiWebhookPolarServerRoute
  AuthedAppPolarPortalServerRoute: typeof AuthedAppPolarPortalServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StaticRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static/': {
      id: '/_static/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StaticIndexRouteImport
      parentRoute: typeof StaticRouteRoute
    }
    '/_static/database/': {
      id: '/_static/database/'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof StaticDatabaseIndexRouteImport
      parentRoute: typeof StaticRouteRoute
    }
    '/_static/auth/': {
      id: '/_static/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof StaticAuthIndexRouteImport
      parentRoute: typeof StaticRouteRoute
    }
    '/_authed/app/': {
      id: '/_authed/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_static/database/queries': {
      id: '/_static/database/queries'
      path: '/database/queries'
      fullPath: '/database/queries'
      preLoaderRoute: typeof StaticDatabaseQueriesRouteImport
      parentRoute: typeof StaticRouteRoute
    }
    '/_static/auth/client': {
      id: '/_static/auth/client'
      path: '/auth/client'
      fullPath: '/auth/client'
      preLoaderRoute: typeof StaticAuthClientRouteImport
      parentRoute: typeof StaticRouteRoute
    }
    '/_authed/app/polar/subscriptions': {
      id: '/_authed/app/polar/subscriptions'
      path: '/app/polar/subscriptions'
      fullPath: '/app/polar/subscriptions'
      preLoaderRoute: typeof AuthedAppPolarSubscriptionsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/app/polar/checkout/success': {
      id: '/_authed/app/polar/checkout/success'
      path: '/app/polar/checkout/success'
      fullPath: '/app/polar/checkout/success'
      preLoaderRoute: typeof AuthedAppPolarCheckoutSuccessRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/webhook/polar': {
      id: '/api/webhook/polar'
      path: '/api/webhook/polar'
      fullPath: '/api/webhook/polar'
      preLoaderRoute: typeof ApiWebhookPolarServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/_authed/app/polar/portal': {
      id: '/_authed/app/polar/portal'
      path: '/app/polar/portal'
      fullPath: '/app/polar/portal'
      preLoaderRoute: typeof AuthedAppPolarPortalServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppPolarSubscriptionsRoute: typeof AuthedAppPolarSubscriptionsRoute
  AuthedAppPolarCheckoutSuccessRoute: typeof AuthedAppPolarCheckoutSuccessRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppPolarSubscriptionsRoute: AuthedAppPolarSubscriptionsRoute,
  AuthedAppPolarCheckoutSuccessRoute: AuthedAppPolarCheckoutSuccessRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface StaticRouteRouteChildren {
  StaticIndexRoute: typeof StaticIndexRoute
  StaticAuthClientRoute: typeof StaticAuthClientRoute
  StaticDatabaseQueriesRoute: typeof StaticDatabaseQueriesRoute
  StaticAuthIndexRoute: typeof StaticAuthIndexRoute
  StaticDatabaseIndexRoute: typeof StaticDatabaseIndexRoute
}

const StaticRouteRouteChildren: StaticRouteRouteChildren = {
  StaticIndexRoute: StaticIndexRoute,
  StaticAuthClientRoute: StaticAuthClientRoute,
  StaticDatabaseQueriesRoute: StaticDatabaseQueriesRoute,
  StaticAuthIndexRoute: StaticAuthIndexRoute,
  StaticDatabaseIndexRoute: StaticDatabaseIndexRoute,
}

const StaticRouteRouteWithChildren = StaticRouteRoute._addFileChildren(
  StaticRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  StaticRouteRoute: StaticRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiWebhookPolarServerRoute: ApiWebhookPolarServerRoute,
  AuthedAppPolarPortalServerRoute: AuthedAppPolarPortalServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
